=== jkenlooper/chillbox/site.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://chillbox.massive.xyz/site.json",
  "type": "object",
  "required": [
    "name",
    "version",
    "git_repo",
    "contact",
    "domain_list"
  ],
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "title": "The name schema",
      "description": "Name of site."
    },
    "version": {
      "type": "string",
      "title": "The version schema",
      "description": "Name of site."
    },
    "contact": {
      "type": "object",
      "title": "The contact schema",
      "description": "Contact",
      "required": [
        "owner",
        "technical"
      ],
      "properties": {
        "owner": {
          "type": "string",
          "title": "The owner schema",
          "description": ""
        },
        "technical": {
          "type": "string",
          "title": "The technical schema",
          "description": ""
        }
      },
      "additionalProperties": false
    },
    "git_repo": {
      "type": "string",
      "title": "The git_repo schema",
      "description": "Name of site."
    },
    "domain_list": {
      "type": "array",
      "title": "The domain_list schema",
      "description": "",
      "additionalItems": true,
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "env": {
      "type": "array",
      "title": "The env schema",
      "description": "",
      "additionalItems": true,
      "items": {
        "type": "object",
        "title": "Name/value",
        "description": "",
        "required": [
          "name",
          "value"
        ],
        "properties": {
          "name": {
            "type": "string",
            "title": "The name schema",
            "description": ""
          },
          "value": {
            "type": "string",
            "title": "The value schema",
            "description": ""
          }
        },
        "additionalProperties": false
      }
    },
    "crontab": {
      "type": "array",
      "title": "The crontab schema",
      "description": "",
      "additionalItems": true,
      "items": {
        "type": "string"
      }
    },
    "services": {
      "type": "array",
      "title": "The services schema",
      "description": "",
      "additionalItems": true,
      "items": {
        "type": "object",
        "title": "The first anyOf schema",
        "description": "",
        "required": [
          "name",
          "lang",
          "handler",
          "environment"
        ],
        "properties": {
          "name": {
            "type": "string",
            "title": "The name schema",
            "description": ""
          },
          "lang": {
            "type": "string",
            "title": "The lang schema",
            "description": ""
          },
          "handler": {
            "type": "string",
            "title": "The handler schema",
            "description": ""
          },
          "secrets_config": {
            "type": "string",
            "title": "The secrets_config schema",
            "description": ""
          },
          "environment": {
            "type": "array",
            "title": "The environment schema",
            "description": "",
            "additionalItems": true,
            "items": {
              "type": "object",
              "title": "Name/value",
              "description": "",
              "required": [
                "name",
                "value"
              ],
              "additionalProperties": false,
              "properties": {
                "name": {
                  "type": "string",
                  "title": "The name schema",
                  "description": ""
                },
                "value": {
                  "type": "string",
                  "title": "The value schema",
                  "description": ""
                }
              }
            }
          }
        }
      }
    }
  }
}

=== jkenlooper/chillbox/tests/fixtures/site1.site.json
{
  "name": "Site One",
  "version": "0.1.0-alpha.1",
  "git_repo": "https://github.com/jkenlooper/www.weboftomorrow.com.git",
  "contact": {
    "owner": "site1@weboftomorrow.com",
    "technical": "site1@weboftomorrow.com"
  },
  "domain_list": [
    "site1.weboftomorrow.com"
  ],
  "env": [
    {
      "name": "SITE1_SERVER_NAME",
      "value": "$server_name"
    },
    {
      "name": "SITE1_SERVER_PORT",
      "value": "$server_port"
    },
    {
      "name": "SITE1_PROXY_INTERCEPT_ERRORS",
      "value": "on"
    },
    {
      "name": "SITE1_VERSION",
      "value": "$version"
    },
    {
      "name": "SITE1_PROXY_CACHE_VALID",
      "value": "1y"
    },
    {
      "name": "SITE1_CHILL",
      "value": "http://localhost:5000"
    },
    {
      "name": "SITE1_API",
      "value": "http://localhost:8084"
    },
    {
     "name": "SITE1_IMMUTABLE__EXAMPLE",
     "value": "$S3_ENDPOINT_URL/$IMMUTABLE_BUCKET_NAME/$slugname/$version/example/"
    }
  ],
  "crontab": [
    "13 5 * * 6 echo 'do something'"
  ],
  "services": [
    {
      "name": "api",
      "lang": "flask",
      "handler": "api",
      "secrets_config": "api.cfg",
      "environment": [
        {
          "name": "SERVER_NAME",
          "value": "$server_name"
        },
        {
          "name": "PORT",
          "value": "8084"
        },
        {
          "name": "FLASK_APP",
          "value": "site1_api.app"
        }
      ]
    },
    {
      "name": "chillstatic",
      "lang": "chill",
      "handler": "chill",
      "environment": [
        {
          "name": "freeze",
          "value": "true"
        },
        {
          "name": "CHILL_HOST",
          "value": "localhost"
        },
        {
          "name": "CHILL_PORT",
          "value": "5000"
        },
        {
          "name": "CHILL_MEDIA_PATH",
          "value": "/media/"
        },
        {
          "name": "CHILL_THEME_STATIC_PATH",
          "value": "/theme/${version}/"
        }
      ]
    },
    {
      "name": "chilldynamic",
      "lang": "chill",
      "handler": "chill",
      "environment": [
        {
          "name": "freeze",
          "value": "false"
        },
        {
          "name": "CHILL_HOST",
          "value": "localhost"
        },
        {
          "name": "CHILL_PORT",
          "value": "5001"
        },
        {
          "name": "CHILL_MEDIA_PATH",
          "value": "/media/"
        },
        {
          "name": "CHILL_THEME_STATIC_PATH",
          "value": "/theme/${version}/"
        }
      ]
    }
  ]
}
