=== jkenlooper/chillbox/src/local/verify-sites/site.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://chillbox.massive.xyz/site.json",
  "type": "object",
  "required": [
    "name",
    "server_name",
    "release",
    "contact",
    "domain_list"
  ],
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "title": "The name schema",
      "description": "Name of site."
    },
    "server_name": {
      "type": "string",
      "title": "Canonical server name",
      "description": "Set to a FQDN"
    },
    "version": {
      "type": "string",
      "title": "Version of the site",
      "description": "The value is replaced here with the output of the 'make inspect.VERSION' command if that has been defined."
    },
    "contact": {
      "type": "object",
      "title": "The contact schema",
      "description": "Contact",
      "required": [
        "owner",
        "technical"
      ],
      "properties": {
        "owner": {
          "type": "string",
          "title": "The owner schema",
          "description": ""
        },
        "technical": {
          "type": "string",
          "title": "The technical schema",
          "description": ""
        }
      },
      "additionalProperties": false
    },
    "release": {
      "type": "string",
      "title": "Release tar.gz file",
      "description": "The URL or absolute file path of the release in a tar.gz format."
    },
    "domain_list": {
      "type": "array",
      "title": "The domain_list schema",
      "description": "",
      "additionalItems": true,
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "env": {
      "type": "array",
      "title": "The env schema",
      "description": "",
      "additionalItems": true,
      "items": {
        "type": "object",
        "title": "Name/value",
        "description": "",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string",
            "title": "The name schema",
            "description": ""
          },
          "value": {
            "type": "string",
            "title": "The value schema",
            "description": "An optional value to set."
          },
          "cmd": {
            "type": "string",
            "title": "The command for the value",
            "description": "An optional command to use to fill in the value at build time."
          }
        },
        "additionalProperties": false
      }
    },
    "crontab": {
      "type": "array",
      "title": "The crontab schema",
      "description": "",
      "additionalItems": true,
      "items": {
        "type": "string"
      }
    },
    "services": {
      "type": "array",
      "title": "The services schema",
      "description": "",
      "additionalItems": true,
      "items": {
        "type": "object",
        "title": "The first anyOf schema",
        "description": "",
        "required": [
          "name",
          "lang",
          "handler",
          "environment"
        ],
        "properties": {
          "name": {
            "type": "string",
            "title": "The name schema",
            "description": ""
          },
          "lang": {
            "enum": [
              "immutable",
              "chill",
              "flask"
            ],
            "title": "The lang schema",
            "description": ""
          },
          "handler": {
            "type": "string",
            "title": "The handler schema",
            "description": ""
          },
          "worker_class": {
            "enum": [
              "sync",
              "gevent",
              "uvicorn.workers.UvicornWorker"
            ],
            "title": "The worker_class schema",
            "description": "Only supports some of the gunicorn worker classes."
          },
          "log_level": {
            "enum": [
              "debug",
              "info",
              "warning",
              "error",
              "critical"
            ],
            "title": "The log_level schema",
            "description": "The log level to pass to gunicorn process manager. https://docs.gunicorn.org/en/latest/settings.html#loglevel"
          },
          "niceness": {
            "type": "integer",
            "maxiumum": 19,
            "miniumum": -20,
            "title": "The niceness schema",
            "description": "The scheduling priority value to assign the process using the 'nice' command. A negative value favors the running service more with a higher scheduling priority."
          },
          "workers": {
            "type": "integer",
            "miniumum": 0,
            "maximum": 12,
            "title": "The workers schema",
            "description": "The initial workers count. https://docs.gunicorn.org/en/latest/design.html#how-many-workers"
          },
          "workers_minimum": {
            "type": "integer",
            "miniumum": 0,
            "title": "The workers_minimum schema",
            "description": "The minimum workers count to use when auto-scaling."
          },
          "workers_maximum": {
            "type": "integer",
            "miniumum": 0,
            "maximum": 12,
            "title": "The workers_maximum schema",
            "description": "The maximum workers count to use when auto-scaling."
          },
          "max_requests": {
            "type": "integer",
            "miniumum": 0,
            "title": "The max_requests schema",
            "description": "The value to pass to gunicorn max-requests. The maximum number of requests a worker will process before restarting."
          },
          "max_requests_jitter": {
            "type": "integer",
            "miniumum": 0,
            "title": "The max_requests_jitter schema",
            "description": "The value to pass to gunicorn max-requests-jitter. The maximum jitter to add to the *max_requests* setting."
          },
          "secrets_config": {
            "type": "string",
            "title": "The secrets_config schema",
            "description": ""
          },
          "secrets_export_dockerfile": {
            "type": "string",
            "title": "The secrets_export_dockerfile schema",
            "description": ""
          },
          "manifest": {
            "type": "string",
            "title": "The manifest schema",
            "description": ""
          },
          "environment": {
            "type": "array",
            "title": "The environment schema",
            "description": "",
            "additionalItems": true,
            "items": {
              "type": "object",
              "title": "Name/value",
              "description": "",
              "required": [
                "name",
                "value"
              ],
              "additionalProperties": false,
              "properties": {
                "name": {
                  "type": "string",
                  "title": "The name schema",
                  "description": ""
                },
                "value": {
                  "type": "string",
                  "title": "The value schema",
                  "description": ""
                }
              }
            }
          }
        }
      }
    }
  }
}

=== jkenlooper/chillbox/tests/fixtures/sites/site1.site.json
{
  "name": "Site One",
  "release": "https://example.test/this_whole_string_is_replaced_with_an_absolute_file_path_in_terra.sh",
  "contact": {
    "owner": "site1@example.test",
    "technical": "site1@example.test"
  },
  "server_name": "site1.example.chill.box",
  "domain_list": [
    "site1.example.chill.box"
  ],
  "env": [
    {
      "name": "CHILL_STATIC",
      "value": "http://localhost:5000"
    },
    {
      "name": "CHILL_DYNAMIC",
      "value": "http://localhost:5001"
    },
    {
      "name": "API",
      "value": "http://localhost:8084"
    },
    {
      "name": "IMMUTABLE_EXAMPLE_URI",
      "value": "/immutable-example/v1/$IMMUTABLE_EXAMPLE_HASH/"
    },
    {
      "name": "IMMUTABLE_EXAMPLE",
      "value": "https://$IMMUTABLE_BUCKET_DOMAIN_NAME/$SLUGNAME/immutable/immutable-example/$IMMUTABLE_EXAMPLE_HASH/"
    },
    {
      "name": "IMMUTABLE_EXAMPLE_HASH",
      "value": "replaced-with-cmd-to-get-hash",
      "cmd": "md5sum ./Makefile | cut -d' ' -f1"
    }
  ],
  "crontab": [
    "13 5 * * 6 echo 'do something'"
  ],
  "services": [
    {
      "name": "api",
      "lang": "flask",
      "handler": "api",
      "secrets_config": "api-bridge.secrets.cfg",
      "secrets_export_dockerfile": "api-bridge.secrets.Dockerfile",
      "environment": [
        {
          "name": "PORT",
          "value": "8084"
        },
        {
          "name": "FLASK_APP",
          "value": "site1_api.app"
        }
      ]
    },
    {
      "name": "chillstatic",
      "lang": "chill",
      "handler": "chill-static-example",
      "environment": [
        {
          "name": "freeze",
          "value": "true"
        },
        {
          "name": "CHILL_HOST",
          "value": "localhost"
        },
        {
          "name": "CHILL_PORT",
          "value": "5000"
        }
      ]
    },
    {
      "name": "chilldynamic",
      "lang": "chill",
      "handler": "chill-dynamic-example",
      "environment": [
        {
          "name": "freeze",
          "value": "false"
        },
        {
          "name": "CHILL_HOST",
          "value": "localhost"
        },
        {
          "name": "CHILL_PORT",
          "value": "5001"
        }
      ]
    }
  ]
}
